#!/usr/bin/env python3

import sys

if sys.version_info[0] < 3 or sys.version_info[1] < 5:
    print("This program requires Python version 3.5 or newer")
    sys.exit(1)

import os
import argparse
from scalaplugin import install_coursier
from common import is_existing_dir
from logger import add_verbosity_arg

def get_parser():
    parser = argparse.ArgumentParser(formatter_class=argparse.RawTextHelpFormatter,
                                     description='Fetch Coursier')
    parser.add_argument('directory', help='directory in which to install Coursier',
                        type=is_existing_dir)
    parser.add_argument('--jar', action='store_true', default=False,
                         help='Download Coursier jar instead of native binary')

    add_verbosity_arg(parser)
    return parser

if __name__ == '__main__':
    parser = get_parser()
    args = parser.parse_args()
    install_coursier(args.directory, jar=args.jar)
